# Aura Uptime Monitor Configuration
# Add any website or endpoint you want to monitor in this list.
#
# Created on: Saturday, August 2, 2025
# Location Context: Meraganj, West Bengal, India

monitors:
  - name: "Google Search"
    url: "https://www.google.com"

  - name: "GitHub"
    url: "https://www.github.com"

  - name: "West Bengal Govt Portal"
    url: "https://wb.gov.in/"

  - name: "Known Failing Site (503)"
    url: "https://httpstat.us/503"

  - name: "Invalid Domain (Error)"
    url: "https://this-domain-does-not-exist-12345.com"
