# check_interval is in seconds. 1800 seconds = 30 minutes.
check_interval: 1800

# Number of history segments to show on the UI.
# This should match the CSS grid in index.html.
history_segments: 48

# List of sites to monitor.
sites:
  - name: "Game Panel"
    url: "https://gamep.cloudcrash.shop/"
  - name: "IN Node"
    url: "https://ccin1.cloudcrash.shop/"
  - name: "SE Node"
    url: "httppsyour-vps-ip-or-domain"
  - name: "Website"
    url: "https://google.com"
